// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV19yrXMfmbBkcHVmamaYVENdoZomnQg',
    appId: '1:784736483376:web:0ee0728f94e895002755f5',
    messagingSenderId: '784736483376',
    projectId: 'jobtrace-app',
    authDomain: 'jobtrace-app.firebaseapp.com',
    storageBucket: 'jobtrace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-izJZcFYKU0jn81vyykn6CuXa2v66aE',
    appId: '1:784736483376:android:bdc157dc66e58a472755f5',
    messagingSenderId: '784736483376',
    projectId: 'jobtrace-app',
    storageBucket: 'jobtrace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3yUjNfwlTR3-Y54e7iZrwjFZZ4jxRzE',
    appId: '1:784736483376:ios:9dfbbbfee157006e2755f5',
    messagingSenderId: '784736483376',
    projectId: 'jobtrace-app',
    storageBucket: 'jobtrace-app.firebasestorage.app',
    iosBundleId: 'com.example.jobtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3yUjNfwlTR3-Y54e7iZrwjFZZ4jxRzE',
    appId: '1:784736483376:ios:9dfbbbfee157006e2755f5',
    messagingSenderId: '784736483376',
    projectId: 'jobtrace-app',
    storageBucket: 'jobtrace-app.firebasestorage.app',
    iosBundleId: 'com.example.jobtracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcV19yrXMfmbBkcHVmamaYVENdoZomnQg',
    appId: '1:784736483376:web:7db351cd25beaf982755f5',
    messagingSenderId: '784736483376',
    projectId: 'jobtrace-app',
    authDomain: 'jobtrace-app.firebaseapp.com',
    storageBucket: 'jobtrace-app.firebasestorage.app',
  );
}
